version: '3.8'

services:
  ccdi-cpi-etl:
    build: .
    container_name: ccdi-cpi-etl
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=us-east-1
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount current directory for development
      - .:/app
      # Mount AWS credentials if available
      - ~/.aws:/home/app/.aws:ro
    working_dir: /app
    command: python main.py
    
  # Service for running database backup
  db-backup:
    build: .
    container_name: ccdi-cpi-db-backup
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=us-east-1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ~/.aws:/home/app/.aws:ro
      # Mount a volume for backup files
      - ./backups:/app/backups
    working_dir: /app
    command: python db.py
