# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: CRDC Data Loader
prefect-version: 3.2.14

# build section allows you to manage and build docker images
build:

# push section allows you to manage if and how this project is uploaded to remote locations
push:

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.set_working_directory:
    directory: /app
# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: etl-pipeline
  version:
  tags: []
  description: CCDI CPI ETL data processing pipeline
  schedule: {}
  entrypoint: main.py:main
  parameters: {}
  work_pool:
    name: ccdi-cpi-2gb-prefect-2.20.3-python3.9
    work_queue_name: default
    job_variables:
      image: "893214465464.dkr.ecr.us-east-1.amazonaws.com/cpi:latest"
  concurrency_limit:
  schedules: []

- name: database-backup
  version:
  tags: []
  description: MySQL database backup using mysqldump
  schedule: {}
  entrypoint: db.py:mysql_backup_flow
  parameters: {}
  work_pool:
    name: ccdi-cpi-2gb-prefect-2.20.3-python3.9
    work_queue_name: default
    job_variables:
      image: "893214465464.dkr.ecr.us-east-1.amazonaws.com/cpi:latest"
  concurrency_limit:
  schedules: []
